DRAFT: Tiled Map loader
maxdevos49/gate-adventures pull request #4
Opened 2024-03-13 01:22 UTC by danielbarnes175

## Summary

## Technical Changes

## Screenshots

## Ticket

2024-03-13 22:02 UTC, maxdevos49 requested changes, later dismissed
@danielbarnes175 can you add some brief instructions on how to use the tile map editor to the readme

2024-03-13 22:02 UTC, maxdevos49 commented on GateAdventures/Engine/Map/TiledMapLoader.cs
> +		string filePath = Path.Combine(content.RootDirectory, mapFilePath);
When I run `dotnet run --project GateAdventure` it fails to find the JSON file.

The resulting path seems to be: `<path-to-where-command-is-run>` + `<content.RootDirectory>` + `<mapFilePath>`.

If I run `dotnet run` inside the GateAdventures folder it works. I think it should work in both situations and not require being inside the Project folder. Desired path ending up being: `<ExecutableFolderPath>` + `<content.RootDirectory>` + `<mapFilePath>`.

2024-03-13 22:02 UTC, maxdevos49 commented on GateAdventures/Game1.cs
> -﻿using Microsoft.Xna.Framework;
I agree I am not a fan of this class being named Game1 but I did like the Program.cs file. What if the `Game1` class was renamed `GateAdventures` and Program.cs was preserved?

2024-03-13 22:02 UTC, maxdevos49 commented on GateAdventures/Engine/Map/Layers.cs
> +﻿using System;
Mostly a nit but I think we should drop `Engine` in this file path

2024-03-13 22:07 UTC, maxdevos49 commented on GateAdventures/Engine/Map/Layers.cs
> +﻿using System;
I retract this

2024-03-13 22:46 UTC, danielbarnes175 commented on GateAdventures/Engine/Map/Layers.cs
> +﻿using System;
Dang it!!

2024-03-13 22:50 UTC, danielbarnes175 commented
@maxdevos49 Comments addressed,
- Added program.cs back in, renamed Main.cs to GateAdventures.cs
- Adjusted the path of the file to use `Path.Combine(AppContext.BaseDirectory, content.RootDirectory, mapFilePath);`
- Got rid of the `Engine` folder and added it back 🙊 
- Added a new `README.md` in the Tiled folder since it made more sense to me to have it separate from the main one. There were also some additional notes I needed to add about how to actually import the map

2024-03-15 00:44 UTC, maxdevos49 commented on GateAdventures/Engine/Map/Layers.cs
> +﻿using System;
Sorry D:

2024-03-15 00:48 UTC, maxdevos49 approved these changes

2024-03-15 00:58 UTC, merged